export const COMIC_STYLES = [
  {
    id: 'shonen',
    name: 'Shōnen Manga',
    description: 'High energy, dynamic action lines, bold linework, screentone shading',
    references: 'Naruto, One Piece, Dragon Ball',
    pagesPerChapter: [18, 22],
    panelsPerPage: [5, 7],
    readingDirection: 'rtl' as const,
    chaptersPerVolume: [8, 12],
    colorMode: 'B&W',
    icon: '⚡',
    emoji: '⚡',
    accentColor: '#EF4444',
    gradient: 'from-manga-red/20 to-sakura-pink/10',
  },
  {
    id: 'shojo',
    name: 'Shōjo Manga',
    description: 'Soft flowing lines, floral effects, elaborate eyes, emotional close-ups',
    references: 'Sailor Moon, Fruits Basket',
    pagesPerChapter: [16, 20],
    panelsPerPage: [4, 6],
    readingDirection: 'rtl' as const,
    chaptersPerVolume: [8, 10],
    colorMode: 'B&W',
    icon: '🌸',
    emoji: '🌸',
    accentColor: '#EC4899',
    gradient: 'from-sakura-pink/20 to-sakura-soft/10',
  },
  {
    id: 'seinen',
    name: 'Seinen Manga',
    description: 'Detailed, realistic proportions, intricate backgrounds, mature themes',
    references: 'Berserk, Vagabond, Vinland Saga',
    pagesPerChapter: [20, 24],
    panelsPerPage: [5, 8],
    readingDirection: 'rtl' as const,
    chaptersPerVolume: [10, 13],
    colorMode: 'B&W',
    icon: '🗡️',
    emoji: '🗡️',
    accentColor: '#64748B',
    gradient: 'from-ink-light/20 to-ink-mid/10',
  },
  {
    id: 'josei',
    name: 'Josei Manga',
    description: 'Elegant linework, realistic proportions, fashion-conscious design',
    references: 'Nana, Paradise Kiss',
    pagesPerChapter: [16, 20],
    panelsPerPage: [4, 6],
    readingDirection: 'rtl' as const,
    chaptersPerVolume: [8, 10],
    colorMode: 'B&W',
    icon: '✨',
    emoji: '✨',
    accentColor: '#F59E0B',
    gradient: 'from-gold-premium/15 to-sakura-soft/10',
  },
  {
    id: 'manhwa',
    name: 'Korean Manhwa',
    description: 'Full color, vertical scroll, soft cel-shading, cinematic compositions',
    references: 'Solo Leveling, Tower of God',
    pagesPerChapter: [60, 80],
    panelsPerPage: [1, 2],
    readingDirection: 'vertical' as const,
    chaptersPerVolume: [40, 60],
    colorMode: 'Color',
    icon: '💎',
    emoji: '🇰🇷',
    accentColor: '#3B82F6',
    gradient: 'from-neon-cyan/15 to-sakura-pink/10',
  },
  {
    id: 'webtoon',
    name: 'Webtoon',
    description: 'Full color, vertical scroll, clean digital art, expressive characters',
    references: 'Lore Olympus, True Beauty',
    pagesPerChapter: [50, 70],
    panelsPerPage: [1, 2],
    readingDirection: 'vertical' as const,
    chaptersPerVolume: [40, 60],
    colorMode: 'Color',
    icon: '📱',
    emoji: '📱',
    accentColor: '#10B981',
    gradient: 'from-forest-green/15 to-neon-cyan/10',
  },
  {
    id: 'american_superhero',
    name: 'American Superhero',
    description: 'Bold muscular anatomy, dynamic poses, heavy inking, vibrant colors',
    references: 'Marvel, DC Comics',
    pagesPerChapter: [20, 24],
    panelsPerPage: [5, 7],
    readingDirection: 'ltr' as const,
    chaptersPerVolume: [20, 24],
    colorMode: 'Color',
    icon: '🦸',
    emoji: '🦸',
    accentColor: '#DC2626',
    gradient: 'from-manga-red/20 to-neon-cyan/10',
  },
  {
    id: 'bd_franco',
    name: 'Bande Dessinée',
    description: 'Ligne claire style, uniform line weight, flat vibrant colors, detailed backgrounds',
    references: 'Tintin, Astérix, Moebius',
    pagesPerChapter: [44, 48],
    panelsPerPage: [8, 12],
    readingDirection: 'ltr' as const,
    chaptersPerVolume: [44, 48],
    colorMode: 'Color',
    icon: '🎭',
    emoji: '🇫🇷',
    accentColor: '#8B5CF6',
    gradient: 'from-gold-premium/15 to-forest-green/10',
  },
  {
    id: 'noir',
    name: 'Noir / Crime',
    description: 'High contrast B&W, heavy shadows, chiaroscuro, gritty textures',
    references: 'Sin City, Criminal',
    pagesPerChapter: [20, 24],
    panelsPerPage: [4, 6],
    readingDirection: 'ltr' as const,
    chaptersPerVolume: [20, 24],
    colorMode: 'B&W',
    icon: '🔫',
    emoji: '🔫',
    accentColor: '#475569',
    gradient: 'from-ink-light/30 to-ink-void/20',
  },
  {
    id: 'horror_manga',
    name: 'Horror Manga',
    description: 'Heavy cross-hatching, extreme close-ups, body horror, oppressive atmosphere',
    references: 'Uzumaki, The Drifting Classroom',
    pagesPerChapter: [18, 24],
    panelsPerPage: [5, 8],
    readingDirection: 'rtl' as const,
    chaptersPerVolume: [8, 12],
    colorMode: 'B&W',
    icon: '👁️',
    emoji: '👁️',
    accentColor: '#991B1B',
    gradient: 'from-manga-red/20 to-ink-void/20',
  },
  {
    id: 'chibi_4koma',
    name: '4-Koma / Chibi',
    description: 'Super-deformed proportions, 4-panel strips, comedic timing',
    references: 'Azumanga Daioh, Lucky Star',
    pagesPerChapter: [8, 12],
    panelsPerPage: [4, 4],
    readingDirection: 'vertical' as const,
    chaptersPerVolume: [8, 12],
    colorMode: 'B&W',
    icon: '😄',
    emoji: '😄',
    accentColor: '#FBBF24',
    gradient: 'from-gold-premium/20 to-sakura-pink/15',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    description: 'Soft washes, visible brush strokes, dreamy palettes, impressionistic',
    references: 'Artistic and literary graphic novels',
    pagesPerChapter: [16, 24],
    panelsPerPage: [3, 5],
    readingDirection: 'ltr' as const,
    chaptersPerVolume: [16, 24],
    colorMode: 'Color',
    icon: '🎨',
    emoji: '🎨',
    accentColor: '#06B6D4',
    gradient: 'from-neon-cyan/10 to-sakura-soft/15',
  },
] as const;

export type ComicStyleId = typeof COMIC_STYLES[number]['id'];
